### ISSUE TITLE
Return json for error responses

### ISSUE THREAD

**Issue by gashcrumb** [redhat-ipaas/ipaas-rest#247] opened 2017-03-28 15:01 UTC
In some cases we don't get back JSON error responses, for example:

```
com.fasterxml.jackson.databind.JsonMappingException: configuredProperties value
 at [Source: io.undertow.servlet.spec.ServletInputStreamImpl@2c784ac8; line: 43, column: 7] (through reference chain: com.redhat.ipaas.model.integration.Integration$Builder[&quot;steps&quot;]-&gt;java.util.ArrayList[0]-&gt;com.redhat.ipaas.model.integration.Step$Builder[&quot;configuredProperties&quot;])
```

Unfortunately the framework we're using for making HTTP requests chokes on this because it assumes JSON responses in all cases.  While I plan on working around this, we really should try and have JSON responses for error conditions as well, raw string values are kinda hard to deal with when showing the user a useful error message.

related to -> https://github.com/redhat-ipaas/ipaas-ui/issues/328

**Comment by gashcrumb** [comment] 2017-03-28 15:05
This is also not ideal:

```
<html><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
</body></html>
```

**Comment by jimmidyson** [comment] 2017-03-28 15:05
Please can we follow the same approach as Kubernetes which returns a defined Status object including status code, message, etc.

**Comment by rhuss** [comment] 2017-03-28 15:48
@gashcrumb Is this the full exception or do you have some more context information for this first issue ? Need to find out the point in the server where this happens.

w.r.t. to the gateway error, this comes from the OpenShift router. On these error messages we dont have much influence, I'm afraid.

Actually I would not rely on a JSON body for everything with HTTP response code != 200. Isn't it that an Ajax error handler is called for the situation above ? IMO a real world 'framework' should be able to cope with non-JSON responses in error cases as this can always happen because we don't have every layer under control (e.g. not the router, not keycloack responses, ...)

Also, the content-type of the response might be useful, but that can probably not used, too.

**Comment by gashcrumb** [comment] 2017-03-28 15:55
Yeah, think this error comes from not having a `configuredProperties` object set on a `Step` in the flow.

And yeah!  was surprised that Restangular assumes json response as well, haven't yet figured out how to work around that.

**Comment by jimmidyson** [comment] 2017-03-28 15:56
@rhuss The REST API should absolutely return a JSON body for any application issues.

As for the 504, we should switch to an async approach, request to update storage (REST API persists) and then poll/event driven updates for status. Normal REST API requests should be as quick as possible.

**Comment by gashcrumb** [comment] 2017-03-28 15:56
Although actually now that I think about it, for that second error that came through fine.  Maybe the Content-Type on the response was being set to JSON even though the body was just a string.  Lemme see if I can force that error again really quick

**Comment by gashcrumb** [comment] 2017-03-28 15:58
K, nope, this would be the `Content-Type` I'd expect for a non-JSON response:

```
Content-Type:text/html
```

**Comment by rhuss** [comment] 2017-03-28 16:12
@jimmibot agreed that we can fix the timeout issue on the gateway, but this won't prevent you the gateway to send other errors that happen in plain html within the body (guess that the point of this issue). I agree that it would be awesome if everybody would send it in a machine readable format, but we should also be prepared when this is not the case (because we cant guarantee that)

**Comment by rhuss** [comment] 2017-03-28 16:15
@gashcrumb back to the original issue: If I understand right this consists of two parts:

* The domain model is missing a property 'configuredProperties' and should be fixed so that this error won't happen.
* For the general case when Jackson can't map JSON to Java then a _proper_ error message should be returned in JSON format. This needs to be figured out serialisation layer.

**Comment by rhuss** [comment] 2017-03-28 16:16
I will look at the generic serialization error stuff.

@KurtStam as you are on the domain model anyway via #246 could you have look to the missing configureProperties on `Step` ?

**Comment by gashcrumb** [comment] 2017-03-28 16:26
> The domain model is missing a property 'configuredProperties' and should be fixed so that this error won't happen.

In this case it's likely my fault, as I'm sending a `configuredProperties` for an HTTP connection with `null` for the URL string value, as I think we've not yet got validation working on the step config page.  So it's a valid error response I think, but it'd be good if it was in JSON.

**Comment by KurtStam** [comment] 2017-03-28 18:14
We need to map all exceptions:
rest/src/main/java/com/redhat/ipaas/rest/v1/handler/exception/

**Comment by jludvice** [comment] 2017-03-30 07:51
Hello @KurtStam. In response to https://github.com/redhat-ipaas/ipaas-ui/issues/328: 
creating integration on **localhost:4200** (using staging ipaas-rest as backend)
Error message: `Response with status: 0  for URL: null`
- the http status is 500
- body is empty 
- stacktrace from ipaas-rest deployment: [ipaas-staging-stacktrace.txt](https://github.com/redhat-ipaas/ipaas-rest/files/881371/ipaas-staging-stacktrace.txt)

creating same integration on **ipaas-qe instance on openshift:**
Error message: 
`Response with status: 500 Internal Server Error for URL: https://ipaas-qe.b6ff.rh-idev.openshiftapps.com/api/v1/integrations`
Stacktrace from ipaas-rest deployment: [stacktrace.txt](https://github.com/redhat-ipaas/ipaas-rest/files/881366/stacktrace.txt)

How is that possible that one error produces 500 lines of stacktraces in logs?
Is this info helpful?

**Comment by KurtStam** [comment] 2017-04-05 16:28
@jludvice yes this is helpful. The issue is that the user that is logged in now touches GitHub and Kubernetes for which he needs to be authenticated and authorized. AFAI understand it we are looking into using offline tokens for this now. So trying to fix this for the sync case is not much use since it's about to change anyway.

This brings up a good point about error handling though. The current code in place to handle to exceptions when using RESTEasy has not been updated now that we are using Spring. So while @iocanel is working on the offline token stuff I will take a look at improving the error handling.

**Closed** 2017-04-13 18:37 UTC
